// Signature Interpretation Keys and Translation dictionaries
// Supports full multi-language translations. English and Hindi are fully translated.
// Other languages have stubs which fallback gracefully to English.

export const SIGNATURE_TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    "signature.title": "Signature Style Diagnostics",
    "signature.subtitle": "Audit handwriting Vastu, trailing lines, ending strokes, and numeric resonance.",
    "signature.disclaimer": "This is not scientific handwriting verification, legal authentication, or psychological diagnosis. It is symbolic, self-reflection, and numerology/Vastu-style guidance.",
    "signature.form.fullName": "Full Name",
    "signature.form.fullNamePlaceholder": "Enter full name for Chaldean vibration",
    "signature.form.dob": "Date of Birth (Recommended)",
    "signature.form.gender": "Gender Alignment",
    "signature.form.gender.male": "Male (Surya)",
    "signature.form.gender.female": "Female (Chandra)",
    "signature.form.gender.other": "Non-Binary (Mercury)",
    "signature.form.mobile": "Mobile Number (Optional)",
    "signature.form.mobilePlaceholder": "10-digit mobile number",
    "signature.form.intent": "Signature Intent & Focus Area",
    "signature.form.intent.career": "Career Growth",
    "signature.form.intent.business": "Business Prosperity",
    "signature.form.intent.finance": "Financial Stability",
    "signature.form.intent.leadership": "Authority / Leadership",
    "signature.form.intent.harmony": "Relationship Harmony",
    "signature.form.intent.general": "General Personality Alignment",
    "signature.form.writingHand": "Writing Hand",
    "signature.form.hand.right": "Right Hand",
    "signature.form.hand.left": "Left Hand",
    "signature.form.hand.ambi": "Ambidextrous",
    "signature.form.hand.unknown": "Unknown / Mixed",
    "signature.form.upload": "Upload Signature Image",
    "signature.form.dragDrop": "Drag and drop signature here or click to browse",
    "signature.form.uploadRules": "Accepts JPG, PNG, WEBP (Max 5MB)",
    "signature.form.removeImage": "Remove Image",
    "signature.form.analyze": "Analyze Signature",
    "signature.form.analyzing": "Running Optical & Celestial Audits...",
    "signature.form.error.imageRequired": "Signature image is required for scanning.",
    "signature.form.error.nameRequired": "Subject full name is required for Chaldean acoustics.",
    "signature.form.error.invalidMobile": "Mobile number must be exactly 10 digits if provided.",

    // Report Headers
    "signature.report.executiveSummary": "Executive Summary",
    "signature.report.overallScore": "Overall Alignment",
    "signature.report.positiveSign": "Main Positive Vibration",
    "signature.report.correctionNeeded": "Critical Correction Needed",
    "signature.report.recommendedDirection": "Recommended Path Forward",
    "signature.report.scoreInterpretation": "Score Interpretation",
    "signature.report.excellent": "Excellent Alignment",
    "signature.report.good": "Good, but can improve",
    "signature.report.mixed": "Mixed / Needs correction",
    "signature.report.correctionRecommended": "Strong correction recommended",

    // Visual Metrics
    "signature.metrics.title": "Visual Signature Reading",
    "signature.metrics.slant": "Signature Slant",
    "signature.metrics.slant.upward": "Upward Ascent",
    "signature.metrics.slant.straight": "Flat Horizon",
    "signature.metrics.slant.downward": "Downward Descent",
    "signature.metrics.underline": "Underline Foundation",
    "signature.metrics.underline.none": "No Underline Detected",
    "signature.metrics.underline.present": "Underline Detected",
    "signature.metrics.underline.cutting": "Cutting Underline (Critical)",
    "signature.metrics.finalDot": "Final Dot / Ending",
    "signature.metrics.finalDot.present": "Final Dot Detected (Blockage Risk)",
    "signature.metrics.finalDot.none": "Open Ending (Progressive)",
    "signature.metrics.starting": "Starting Stroke",
    "signature.metrics.starting.complex": "Cluttered / Dense Start",
    "signature.metrics.starting.clean": "Clean & Open Start",
    "signature.metrics.loops": "Loops & Flourishes",
    "signature.metrics.loops.tall": "Tall Professional Loops",
    "signature.metrics.loops.excessive": "Excessive Crossings",
    "signature.metrics.loops.balanced": "Balanced Fluid Loops",
    "signature.metrics.readability": "Readability",
    "signature.metrics.readability.clear": "Clear Name Projection",
    "signature.metrics.readability.moderate": "Moderately Legible",
    "signature.metrics.readability.unclear": "Hidden Professional Identity",
    "signature.metrics.pressure": "Pen Pressure & Flow",
    "signature.metrics.pressure.heavy": "Heavy Pressure (High Stress)",
    "signature.metrics.pressure.medium": "Balanced Steady Pressure",
    "signature.metrics.pressure.light": "Light Flowing Pressure",
    "signature.metrics.spacing": "Character Spacing",

    // Numerology
    "signature.num.title": "Numerological Coordinate Alignment",
    "signature.num.chaldean": "Chaldean Name Value",
    "signature.num.driver": "Psychic Driver (Mulank)",
    "signature.num.conductor": "Destiny Conductor (Bhagyank)",
    "signature.num.style": "Compatible Signature Style",
    "signature.num.angle": "Lucky Signature Angle",
    "signature.num.initials": "Initials Visibility",
    "signature.num.color": "Recommended Ink Colour",

    // Intent interpretations
    "signature.scores.title": "Astro-Functional Interpretations",
    "signature.scores.career": "Career Growth",
    "signature.scores.prosperity": "Business Prosperity",
    "signature.scores.finance": "Financial Stability",
    "signature.scores.authority": "Authority & Command",
    "signature.scores.communication": "Communication Clarity",
    "signature.scores.relationship": "Relationship Harmony",

    // Corrections
    "signature.corrections.title": "Signature Corrections & Remodeling",
    "signature.corrections.keep": "Keep & Maintain",
    "signature.corrections.remove": "Erase & Remove",
    "signature.corrections.improve": "Improve & Polish",

    // Formulas and practice plans
    "signature.formula.title": "Corrected Signature Formula",
    "signature.practice.title": "Daily Practice Blueprint",
    "signature.practice.desc": "To lock in these structural corrections and rewrite your vibrational sub-planes:",
    "signature.practice.rule1": "Practice writing your new signature exactly 21 times daily for 21 consecutive days.",
    "signature.practice.rule2": "Always use a high-quality pen with recommended ink.",
    "signature.practice.rule3": "Keep unruled paper specifically for this practice.",
    "signature.practice.rule4": "Sign with conscious intent and focus on your target area.",

    "signature.print.button": "Print / Save Signature Report as PDF",

    // Observations keys
    "signature.obs.slant.upward.title": "Upward Ambition Slant",
    "signature.obs.slant.upward.desc": "Your signature rises upwards from left to right. This shows strong ambition, optimism, and progressive career rise. It allows solar and Jovian energy flow.",
    "signature.obs.slant.neutralRising.title": "Neutral body with Rising Support",
    "signature.obs.slant.neutralRising.desc": "Your main letter body is straight and stable, while the underline climbs upwards. This represents a highly balanced personal character supported by positive growth energy.",
    "signature.obs.slant.downward.title": "Downward Descent Trap",
    "signature.obs.slant.downward.desc": "A downward slope indicates blocked momentum, declining stamina, or self-doubt at critical moments. It siphons wealth and drains material energy.",
    "signature.obs.slant.straight.title": "Flat Stable Horizon",
    "signature.obs.slant.straight.desc": "A horizontal signature indicates stable emotions, strong balance, and high reliability. However, it may sometimes lack progressive expansion drive.",
    "signature.slant.upward.description": "Your signature rises upwards from left to right. This shows strong ambition, optimism, and progressive career rise. It allows solar and Jovian energy flow.",
    "signature.slant.horizontal.description": "A horizontal signature indicates stable emotions, strong balance, and high reliability. However, it may sometimes lack progressive expansion drive.",
    "signature.slant.downward.description": "A downward slope indicates blocked momentum, declining stamina, or self-doubt at critical moments. It siphons wealth and drains material energy.",
    
    "signature.obs.underline.present.title": "Confident Foundation",
    "signature.obs.underline.present.desc": "A clean underline underneath your name provides a cosmic foundation, indicating strong self-support, professional recognition, and reliability.",
    "signature.obs.underline.none.title": "Independent Self-Reliance",
    "signature.obs.underline.none.desc": "The lack of an underline suggests you prefer carving your path without depending on others. However, adding an underline can increase planetary stability.",
    "signature.obs.underline.cuts.title": "Self-Created Obstacles",
    "signature.obs.underline.cuts.desc": "The underline cuts through the lower loops of your name. This suggests self-created pressure, unnecessary obstacles, or severe leak of energy.",

    "signature.obs.dot.present.title": "Terminal Energy Barrier",
    "signature.obs.dot.present.desc": "A dot at the end of a signature acts as a cosmic full-stop. It suggests overthinking, professional halts, or a tendency to block fresh opportunities.",
    "signature.obs.dot.none.title": "Progressive Open Ending",
    "signature.obs.dot.none.desc": "An open and rising final stroke allows energies to flow freely. It invites unexpected opportunities and progressive material scaling.",

    "signature.obs.starting.complex.title": "Scattered Beginnings",
    "signature.obs.starting.complex.desc": "High clutter or crossing loops at the beginning suggest initial confusion, struggle before success, or scattered planning.",
    "signature.obs.starting.clean.title": "Clear Starting Intention",
    "signature.obs.starting.clean.desc": "A clean, open initial letter allows direct execution, showing clarity in goals and rapid administrative approvals.",

    "signature.obs.readability.clear.title": "Transparent Credibility",
    "signature.obs.readability.clear.desc": "A highly legible signature projects honest intentions, self-acceptance, and clear professional standing, which builds strong trust.",
    "signature.obs.readability.moderate.desc": "Moderate readability shows a balance between personal privacy and public identity. It protects inner vulnerability while allowing essential trust.",
    "signature.obs.readability.unclear.title": "Guarded Professional Identity",
    "signature.obs.readability.unclear.desc": "Low readability suggests extreme discretion, a guarded persona, or difficulty in sharing plans with others. It may create trust gaps.",

    "signature.obs.pressure.heavy.title": "Stressful Force",
    "signature.obs.pressure.heavy.desc": "Extremely heavy pressure shows deep intensity, strong willpower, but also potential blockages of mental peace and high friction.",
    "signature.obs.pressure.medium.title": "Balanced Steady Pressure",
    "signature.obs.pressure.medium.desc": "Moderate steady pressure represents stable willpower, balanced vitality, and controlled emotions. It shows high adaptability and social grace.",
    "signature.obs.pressure.light.title": "Sensitive Adaptability",
    "signature.obs.pressure.light.desc": "Light pen pressure suggests a gentle, adaptable nature, high empathy, but occasionally a lack of execution force or stamina."
  },
  hi: {
    "signature.title": "हस्ताक्षर शैली निदान",
    "signature.subtitle": "हस्ताक्षर के झुकाव, रेखा, अंतिम स्ट्रोक और अंक-ज्योतिषीय गूंज का विश्लेषण करें।",
    "signature.disclaimer": "यह वैज्ञानिक हस्तलेखन सत्यापन या कानूनी प्रमाणीकरण नहीं है। यह प्रतीकात्मक, ग्राफोलॉजी और वास्तु-शैली का मार्गदर्शन है।",
    "signature.form.fullName": "पूरा नाम",
    "signature.form.fullNamePlaceholder": "शाल्डियन कंपन के लिए पूरा नाम दर्ज करें",
    "signature.form.dob": "जन्म तिथि (अनुशंसित)",
    "signature.form.gender": "लिंग संरेखण",
    "signature.form.gender.male": "पुरुष (सूर्य)",
    "signature.form.gender.female": "महिला (चंद्र)",
    "signature.form.gender.other": "गैर-बाइनरी (बुध)",
    "signature.form.mobile": "मोबाइल नंबर (वैकल्पिक)",
    "signature.form.mobilePlaceholder": "10 अंकों का मोबाइल नंबर",
    "signature.form.intent": "हस्ताक्षर का उद्देश्य एवं फोकस",
    "signature.form.intent.career": "करियर में वृद्धि (Career)",
    "signature.form.intent.business": "व्यवसाय समृद्धि (Business)",
    "signature.form.intent.finance": "वित्तीय स्थिरता (Finance)",
    "signature.form.intent.leadership": "अधिकार और नेतृत्व (Authority)",
    "signature.form.intent.harmony": "संबंधों में सामंजस्य (Harmony)",
    "signature.form.intent.general": "सामान्य व्यक्तित्व संरेखण",
    "signature.form.writingHand": "लिखने वाला हाथ",
    "signature.form.hand.right": "दाहिना हाथ",
    "signature.form.hand.left": "बायां हाथ",
    "signature.form.hand.ambi": "दोनों हाथ",
    "signature.form.hand.unknown": "अज्ञात",
    "signature.form.upload": "हस्ताक्षर छवि अपलोड करें",
    "signature.form.dragDrop": "हस्ताक्षर छवि को यहाँ खींचें या ब्राउज़ करें",
    "signature.form.uploadRules": "JPG, PNG, WEBP स्वीकार्य (अधिकतम 5MB)",
    "signature.form.removeImage": "छवि हटाएं",
    "signature.form.analyze": "हस्ताक्षर विश्लेषण करें",
    "signature.form.analyzing": "ऑप्टिकल और खगोलीय ऑडिट जारी...",
    "signature.form.error.imageRequired": "स्कैनिंग के लिए हस्ताक्षर की छवि आवश्यक है।",
    "signature.form.error.nameRequired": "शाल्डियन कंपन के लिए पूरा नाम आवश्यक है।",
    "signature.form.error.invalidMobile": "यदि मोबाइल नंबर दिया गया है, तो वह ठीक 10 अंकों का होना चाहिए।",

    "signature.report.executiveSummary": "मुख्य सारांश",
    "signature.report.overallScore": "समग्र संरेखण",
    "signature.report.positiveSign": "मुख्य सकारात्मक प्रभाव",
    "signature.report.correctionNeeded": "महत्वपूर्ण सुधार आवश्यक",
    "signature.report.recommendedDirection": "अनुशंसित सुधारात्मक मार्ग",
    "signature.report.scoreInterpretation": "अंक की व्याख्या",
    "signature.report.excellent": "उत्कृष्ट संरेखण",
    "signature.report.good": "अच्छा, लेकिन सुधार संभव है",
    "signature.report.mixed": "मिश्रित / सुधार की आवश्यकता",
    "signature.report.correctionRecommended": "मजबूत सुधार की सिफारिश की जाती है",

    "signature.metrics.title": "हस्ताक्षर दृश्य पाठन",
    "signature.metrics.slant": "हस्ताक्षर का झुकाव",
    "signature.metrics.slant.upward": "ऊपर की ओर झुकाव",
    "signature.metrics.slant.straight": "समतल क्षितिज",
    "signature.metrics.slant.downward": "नीचे की ओर झुकाव",
    "signature.metrics.underline": "रेखांकन आधार (Underline)",
    "signature.metrics.underline.none": "कोई रेखा नहीं पाई गई",
    "signature.metrics.underline.present": "सहायक रेखा उपस्थित",
    "signature.metrics.underline.cutting": "काटती हुई रेखा (गंभीर)",
    "signature.metrics.finalDot": "अंतिम बिंदु / समाप्ति",
    "signature.metrics.finalDot.present": "अंतिम बिंदु उपस्थित (अवरोध जोखिम)",
    "signature.metrics.finalDot.none": "खुला अंत (प्रगतिशील)",
    "signature.metrics.starting": "प्रारंभिक स्ट्रोक",
    "signature.metrics.starting.complex": "जटिल / घना प्रारंभ",
    "signature.metrics.starting.clean": "स्वच्छ और खुला प्रारंभ",
    "signature.metrics.loops": "लूप और सजावट",
    "signature.metrics.loops.tall": "लंबे पेशेवर लूप",
    "signature.metrics.loops.excessive": "अत्यधिक क्रॉसिंग",
    "signature.metrics.loops.balanced": "संतुलित तरल लूप",
    "signature.metrics.readability": "पठनीयता",
    "signature.metrics.readability.clear": "स्पष्ट नाम प्रोजेक्शन",
    "signature.metrics.readability.moderate": "मध्यम पठनीय",
    "signature.metrics.readability.unclear": "छिपी हुई पेशेवर पहचान",
    "signature.metrics.pressure": "पेन का दबाव और प्रवाह",
    "signature.metrics.pressure.heavy": "भारी दबाव (उच्च तनाव)",
    "signature.metrics.pressure.medium": "संतुलित स्थिर दबाव",
    "signature.metrics.pressure.light": "हल्का बहता हुआ दबाव",
    "signature.metrics.spacing": "अक्षरों के बीच का स्थान",

    "signature.num.title": "अंक-ज्योतिषीय संरेखण",
    "signature.num.chaldean": "शाल्डियन नाम कंपन मान",
    "signature.num.driver": "ड्राइवर अंक (मूलांक)",
    "signature.num.conductor": "कंडक्टर अंक (भाग्यांक)",
    "signature.num.style": "संगत हस्ताक्षर शैली",
    "signature.num.angle": "भाग्यशाली हस्ताक्षर कोण",
    "signature.num.initials": "प्रारंभिक अक्षरों की दृश्यता",
    "signature.num.color": "अनुशंसित स्याही का रंग",

    "signature.scores.title": "एस्ट्रो-कार्यात्मक व्याख्याएं",
    "signature.scores.career": "करियर विकास",
    "signature.scores.prosperity": "व्यावसायिक समृद्धि",
    "signature.scores.finance": "वित्तीय स्थिरता",
    "signature.scores.authority": "अधिकार और कमान",
    "signature.scores.communication": "संचार स्पष्टता",
    "signature.scores.relationship": "संबंधों में सद्भाव",

    "signature.corrections.title": "हस्ताक्षर सुधार और पुनरुद्धार",
    "signature.corrections.keep": "इसे बनाए रखें",
    "signature.corrections.remove": "इसे हटाएं / मिटाएं",
    "signature.corrections.improve": "इसे सुधारें",

    "signature.formula.title": "संशोधित हस्ताक्षर सूत्र",
    "signature.practice.title": "दैनिक अभ्यास योजना",
    "signature.practice.desc": "इन संरचनात्मक सुधारों को अपने अवचेतन में स्थापित करने के लिए:",
    "signature.practice.rule1": "अपने नए हस्ताक्षर को लगातार 21 दिनों तक प्रतिदिन ठीक 21 बार लिखने का अभ्यास करें।",
    "signature.practice.rule2": "हमेशा अनुशंसित स्याही वाले उच्च गुणवत्ता वाले पेन का ही उपयोग करें।",
    "signature.practice.rule3": "इस अभ्यास के लिए विशेष रूप से बिना रेखा वाली (unruled) कोरी शीट रखें।",
    "signature.practice.rule4": "अपने लक्ष्य क्षेत्र पर ध्यान केंद्रित करते हुए सचेत भाव से हस्ताक्षर करें।",

    "signature.print.button": "प्रिंट करें / हस्ताक्षर रिपोर्ट को PDF के रूप में सहेजें",

    "signature.obs.slant.upward.title": "ऊपर उठता हुआ हस्ताक्षर",
    "signature.obs.slant.upward.desc": "आपका हस्ताक्षर बाएं से दाएं ऊपर की ओर बढ़ता है, जो महत्वाकांक्षा, विकास और करियर में आगे बढ़ने की ऊर्जा को दर्शाता है। यह सूर्य और बृहस्पति की ऊर्जा को आकर्षित करता है।",
    "signature.obs.slant.neutralRising.title": "उठती हुई सहायक रेखा के साथ संतुलित मुख्य भाग",
    "signature.obs.slant.neutralRising.desc": "आपका मुख्य भाग सीधा और स्थिर है, जबकि नीचे की रेखा ऊपर की ओर बढ़ती है। यह सकारात्मक विकास ऊर्जा द्वारा समर्थित एक संतुलित व्यक्तिगत चरित्र का प्रतिनिधित्व करता है।",
    "signature.obs.slant.downward.title": "नीचे गिरता हुआ हस्ताक्षर",
    "signature.obs.slant.downward.desc": "नीचे की ओर झुकाव गिरते हुए आत्मविश्वास, थकान, या महत्वपूर्ण क्षणों में आत्म-संदेह का संकेत माना जाता है। यह धन संचय को रोकता है और ऊर्जा को नष्ट करता है।",
    "signature.obs.slant.straight.title": "समतल स्थिर हस्ताक्षर",
    "signature.obs.slant.straight.desc": "एक समतल हस्ताक्षर मजबूत मानसिक संतुलन, भावनात्मक स्थिरता और विश्वसनीयता को दर्शाता है। हालांकि, इसमें कभी-कभी तेजी से बढ़ने की महत्वाकांक्षा की कमी हो सकती है।",
    "signature.slant.upward.description": "आपका हस्ताक्षर बाएं से दाएं ऊपर की ओर बढ़ता है, जो महत्वाकांक्षा, विकास और करियर में आगे बढ़ने की ऊर्जा को दर्शाता है। यह सूर्य और बृहस्पति की ऊर्जा को आकर्षित करता है।",
    "signature.slant.horizontal.description": "एक समतल हस्ताक्षर मजबूत मानसिक संतुलन, भावनात्मक स्थिरता और विश्वसनीयता को दर्शाता है। हालांकि, इसमें कभी-कभी तेजी से बढ़ने की महत्वाकांक्षा की कमी हो सकती है।",
    "signature.slant.downward.description": "नीचे की ओर झुकाव गिरते हुए आत्मविश्वास, थकान, या महत्वपूर्ण क्षणों में आत्म-संदेह का संकेत माना जाता है। यह धन संचय को रोकता है और ऊर्जा को नष्ट करता है।",

    "signature.obs.underline.present.title": "आत्मविश्वास की नींव",
    "signature.obs.underline.present.desc": "नाम के नीचे खींची गई साफ रेखा एक मजबूत ब्रह्मांडीय नींव प्रदान करती है। यह आत्मनिर्भरता, पेशेवर पहचान और सामाजिक प्रतिष्ठा को दर्शाती है।",
    "signature.obs.underline.none.title": "स्वतंत्र आत्मनिर्भरता",
    "signature.obs.underline.none.desc": "रेखा के अभाव से पता चलता है कि आप दूसरों पर निर्भर हुए बिना अपना रास्ता बनाना पसंद करते हैं। हालांकि, एक सहायक रेखा जोड़ने से जीवन में स्थिरता बढ़ती है।",
    "signature.obs.underline.cuts.title": "हस्ताक्षर को काटती हुई रेखा",
    "signature.obs.underline.cuts.desc": "जब रेखा नाम के निचले हिस्से को काटती है, तो यह आत्म-निर्मित बाधाओं, मानसिक दबाव या धन के अपव्यय की ओर इशारा करती है। रेखा को नाम के नीचे बिना छुए रखें।",

    "signature.obs.dot.present.title": "अंतिम बिंदु अवरोध",
    "signature.obs.dot.present.desc": "हस्ताक्षर के अंत में बिंदु ऊर्जा को रोकने या विकास पर पूर्ण विराम लगाने का संकेत है। यह अति-विचार और अवसरों के टलने का संकेत देता है। इसे हटाना बेहतर है।",
    "signature.obs.dot.none.title": "प्रगतिशील खुला अंत",
    "signature.obs.dot.none.desc": "अंतिम स्ट्रोक खुला और ऊपर उठता हुआ रखने से सकारात्मक ऊर्जा अबाधित बहती है। यह नए वित्तीय अवसरों और जीवन में प्रगति का निमंत्रण है।",

    "signature.obs.starting.complex.title": "बिखरी हुई शुरुआत",
    "signature.obs.starting.complex.desc": "हस्ताक्षर के प्रारंभ में अत्यधिक जटिलता या कटने वाली रेखाएं शुरुआती उलझन, योजना बनाने में कठिनाई या सफलता से पहले अत्यधिक संघर्ष की ओर इशारा करती हैं।",
    "signature.obs.starting.clean.title": "स्पष्ट प्रारंभिक इरादा",
    "signature.obs.starting.clean.desc": "पहला अक्षर बड़ा और साफ रखने से त्वरित निर्णय लेने की क्षमता आती है। यह प्रशासनिक मंजूरी और लक्ष्यों की स्पष्टता सुनिश्चित करता है।",

    "signature.obs.readability.clear.title": "पारदर्शी विश्वसनीयता",
    "signature.obs.readability.clear.desc": "अत्यधिक पठनीय हस्ताक्षर ईमानदार इरादों, खुद को स्वीकार करने और मजबूत व्यावसायिक विश्वसनीयता को प्रोजेक्ट करता है, जो गहरा विश्वास पैदा करता है।",
    "signature.obs.readability.moderate.desc": "मध्यम पठनीयता व्यक्तिगत गोपनीयता और सार्वजनिक पहचान के बीच संतुलन दर्शाती है। यह आवश्यक विश्वास की अनुमति देते हुए आंतरिक संवेदनशीलता की रक्षा करती है।",
    "signature.obs.readability.unclear.title": "अति सुरक्षित व्यावसायिक छवि",
    "signature.obs.readability.unclear.desc": "कम पठनीयता अत्यधिक गोपनीयता या आत्म-सुरक्षा की भावना को दर्शाती है। यह आपके पेशेवर जीवन में विश्वसनीयता या विश्वास की कमी पैदा कर सकता है।",

    "signature.obs.pressure.heavy.title": "अत्यधिक तनावपूर्ण दबाव",
    "signature.obs.pressure.heavy.desc": "पेन का बहुत भारी दबाव मजबूत इच्छाशक्ति दिखाता है, लेकिन यह मानसिक अशांति, आंतरिक क्रोध और जीवन में अत्यधिक घर्षण का भी प्रतीक है।",
    "signature.obs.pressure.medium.title": "संतुलित स्थिर दबाव",
    "signature.obs.pressure.medium.desc": "मध्यम स्थिर दबाव स्थिर इच्छाशक्ति, संतुलित जीवन शक्ति और नियंत्रित भावनाओं का प्रतिनिधित्व करता है। यह उच्च अनुकूलन क्षमता और सामाजिक शालीनता को दर्शाता है।",
    "signature.obs.pressure.light.title": "संवेदनशील अनुकूलनशीलता",
    "signature.obs.pressure.light.desc": "पेन का बहुत हल्का दबाव संवेदनशील स्वभाव, सहानुभूति की भावना, लेकिन कभी-कभी शारीरिक ऊर्जा या मजबूत इच्छाशक्ति की कमी को भी दर्शाता है।"
  }
};

// Return translated string for a key, falling back to English first then key itself
export function getTranslatedKey(lang: string, key: string): string {
  const normalizedLang = lang === "hi" ? "hi" : "en"; // Support other languages falling back to english
  const dict = SIGNATURE_TRANSLATIONS[normalizedLang] || SIGNATURE_TRANSLATIONS["en"];
  return dict[key] || SIGNATURE_TRANSLATIONS["en"][key] || key;
}
